# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15)),
                ('album', models.CharField(max_length=40)),
                ('song', models.CharField(max_length=128)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
